name = "telegrambot"
compatibility_date = "2024-03-25"
pages_build_output_dir = "./dist"
[vars]
BOT_TOKEN = "7883039834:AAHvQKqu1029p8yNrjOSBqFGajWp28sVih0"
BOT_SECRET = "qeruigyqeoirghqewirugp23789er"

[dev]
port = 4444